using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;
using System.Web;
using System.Web.UI;
using InfoCaster.Umbraco.UrlTracker;

[assembly: AssemblyTitle("InfoCaster UrlTracker")]
[assembly: AssemblyDescription("UrlTracker for Umbraco")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("InfoCaster")]
[assembly: AssemblyProduct("UrlTracker")]
[assembly: AssemblyCopyright("© InfoCaster")]
[assembly: AssemblyTrademark("")]
[assembly: ComVisible(false)]
[assembly: Guid("F0A031A5-3DC0-4B41-8029-7D45C4F47F1E")]
[assembly: AssemblyInformationalVersion("4.0.240+Branch.master.Sha.31bfa237b206c01f6f088db9285770440cc12d90")]
[assembly: WebResource("InfoCaster.Umbraco.UrlTracker.SQL.MicrosoftSqlServer.create-table-1.sql", "text/plain")]
[assembly: WebResource("InfoCaster.Umbraco.UrlTracker.SQL.MicrosoftSqlServer.update-table-1.sql", "text/plain")]
[assembly: WebResource("InfoCaster.Umbraco.UrlTracker.SQL.MicrosoftSqlServer.update-table-2.sql", "text/plain")]
[assembly: WebResource("InfoCaster.Umbraco.UrlTracker.SQL.MicrosoftSqlServer.update-table-3.sql", "text/plain")]
[assembly: WebResource("InfoCaster.Umbraco.UrlTracker.SQL.SqlServerCompact.create-table-1.sql", "text/plain")]
[assembly: WebResource("InfoCaster.Umbraco.UrlTracker.SQL.SqlServerCompact.check-table-1.sql", "text/plain")]
[assembly: WebResource("InfoCaster.Umbraco.UrlTracker.SQL.SqlServerCompact.check-table-2.sql", "text/plain")]
[assembly: WebResource("InfoCaster.Umbraco.UrlTracker.SQL.SqlServerCompact.update-table-1.sql", "text/plain")]
[assembly: WebResource("InfoCaster.Umbraco.UrlTracker.SQL.SqlServerCompact.update-table-2.sql", "text/plain")]
[assembly: WebResource("InfoCaster.Umbraco.UrlTracker.UI.res.css.bootstrap.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("InfoCaster.Umbraco.UrlTracker.UI.res.css.bootstrap.min.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("InfoCaster.Umbraco.UrlTracker.UI.res.css.installer.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("InfoCaster.Umbraco.UrlTracker.UI.res.css.info.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("InfoCaster.Umbraco.UrlTracker.UI.res.css.urltracker.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("InfoCaster.Umbraco.UrlTracker.UI.res.img.asc-hover.png", "image/png")]
[assembly: WebResource("InfoCaster.Umbraco.UrlTracker.UI.res.img.asc.png", "image/png")]
[assembly: WebResource("InfoCaster.Umbraco.UrlTracker.UI.res.img.cross.png", "image/png")]
[assembly: WebResource("InfoCaster.Umbraco.UrlTracker.UI.res.img.desc-hover.png", "image/png")]
[assembly: WebResource("InfoCaster.Umbraco.UrlTracker.UI.res.img.desc.png", "image/png")]
[assembly: WebResource("InfoCaster.Umbraco.UrlTracker.UI.res.img.edit.png", "image/png")]
[assembly: WebResource("InfoCaster.Umbraco.UrlTracker.UI.res.img.glyphicons-halflings-white.png", "image/png")]
[assembly: WebResource("InfoCaster.Umbraco.UrlTracker.UI.res.img.glyphicons-halflings.png", "image/png")]
[assembly: WebResource("InfoCaster.Umbraco.UrlTracker.UI.res.img.info.png", "image/png")]
[assembly: WebResource("InfoCaster.Umbraco.UrlTracker.UI.res.img.trash.png", "image/png")]
[assembly: WebResource("InfoCaster.Umbraco.UrlTracker.UI.res.img.urltracker-icon.png", "image/png")]
[assembly: WebResource("InfoCaster.Umbraco.UrlTracker.UI.res.img.urltracker.png", "image/png")]
[assembly: WebResource("InfoCaster.Umbraco.UrlTracker.UI.res.js.bootstrap.js", "text/javascript")]
[assembly: WebResource("InfoCaster.Umbraco.UrlTracker.UI.res.js.bootstrap.min.js", "text/javascript")]
[assembly: WebResource("InfoCaster.Umbraco.UrlTracker.UI.res.js.installer.js", "text/javascript")]
[assembly: WebResource("InfoCaster.Umbraco.UrlTracker.UI.res.js.jquery-1.11.2.min.js", "text/javascript")]
[assembly: WebResource("InfoCaster.Umbraco.UrlTracker.UI.res.js.jquery-migrate-1.2.1.min.js", "text/javascript")]
[assembly: WebResource("InfoCaster.Umbraco.UrlTracker.UI.res.js.jquery.validate.additional-methods.js", "text/javascript")]
[assembly: WebResource("InfoCaster.Umbraco.UrlTracker.UI.res.js.jquery.validate.additional-methods.min.js", "text/javascript")]
[assembly: WebResource("InfoCaster.Umbraco.UrlTracker.UI.res.js.jquery.validate.js", "text/javascript")]
[assembly: WebResource("InfoCaster.Umbraco.UrlTracker.UI.res.js.jquery.validate.min.js", "text/javascript")]
[assembly: WebResource("InfoCaster.Umbraco.UrlTracker.UI.res.js.main.js", "text/javascript")]
[assembly: AssemblyFileVersion("4.0.240.0")]
[assembly: PreApplicationStartMethod(typeof(UrlTrackerPreApplicationStart), "PreApplicationStart")]
[assembly: AssemblyVersion("4.0.240.0")]
